# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src/NHapi.Base"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/ModelGenerator"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/NHapi.SourceGeneration"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/tests/NHapi.Base.NUnit"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/tests/NHapi.NUnit"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/tests/NHapi.NUnit.SourceGeneration"
    schedule:
      interval: "weekly"
